### PR TITLE
vello_cpu: Tweak behavior for filter layers with zero clips

### LINKED ISSUE #1421: vello_cpu: Unreachable code reached
While trying to find a minimal example for #1417, I stumbled upon a different panic for the following test:

```rs
#[vello_test(width = 512, height = 4)]
fn debug_test(ctx: &mut impl Renderer) {
    let filter_gaussian_blur = Filter::from_primitive(FilterPrimitive::GaussianBlur {
        std_deviation: 10.0,
        edge_mode: EdgeMode::None,
    });

    let path_2 = Rect::new(1.0, 1.0, 500.0, 3.0).to_path(0.1);
    let clip_path_1 = Rect::new(0.0, -5.0, 100.0, -3.0).to_path(0.1);

    ctx.push_layer(Some(&clip_path_1), None, None, None, Some(filter_gaussian_blur));
    ctx.fill_path(&path_2);
    ctx.pop_layer();
}
```

```
thread 'filter::debug_test_cpu_u8_scalar' (8668100) panicked at sparse_strips/vello_cpu/src/fine/mod.rs:614:17:
internal error: entered unreachable code
```

This one seems to trace back to: https://github.com/linebender/vello/commit/7816a37c

CC @grebmeg

### PR DESCRIPTION
**Pull request by laurenz-canva**
Closes #1421. The problematic command trace looks as follows:

image

Using the current logic, when we hit a filter layer followed by `PushZeroClip`, we simply increase the command index by one. The render range is 4..4, so afterwards we would simply skip to the `Filter` command that follows `PushZeroClip`. However, as you can see there still is a `PopZeroClip` command.

I think the correct behavior is to completely skip all commands of the layer and jump to the very last `PopBuf` command, which is then executed to ensure the previously pushed (empty) buffer is freed again.

### CODE REVIEW

File: sparse_strips/vello_cpu/src/dispatch/single_threaded.rs [hunk 1]
```diff
@@ -317,7 +317,12 @@ impl SingleThreadedDispatcher {
                     // since this tile is entirely clipped out.
                     // (PushZeroClip only appears for clipped filter layers)
                     Some(Cmd::PushZeroClip(id)) if *id == *child_layer_id => {
-                        cmd_idx += 1; // Skip the PushZeroClip command
+                        // If we have a zero-clip, it means that the whole layer should not be drawn.
+                        // Therefore, we want to skip to the very end so that only `PopBuf` will
+                        // be run. Therefore, we would have to do `filtered_ranges.full_range.end - 1`.
+                        // However, after the match statement we use `cmd_idx + 1` to determine the
+                        // command index, so we actually need to subtract 2 here.
+                        cmd_idx = filtered_ranges.full_range.end - 2;
```
Comment (grebmeg) [inline sparse_strips/vello_cpu/src/dispatch/single_threaded.rs]: What about the approach below? With `continue`, we skip line 357 entirely. So `full_range.end - 1` is just the `PopBuf` index — direct, no dependency on downstream code.

```suggestion
                        // Jump to PopBuf to pop the blend buffer pushed above,
                        // skipping all commands in between.
                        cmd_idx = filtered_ranges.full_range.end - 1;
                        continue;
```

Comment (LaurenzV) [reply sparse_strips/vello_cpu/src/dispatch/single_threaded.rs]: Works for me, did it this way because I thought it might be better if branches use the same path.
