### PR TITLE
vello_common: Harden gradient validation

### LINKED ISSUE #1302: Panic rendering gradients
I'm seeing a few panics in the current gradient LUT code in `vello_cpu`.

May be fixed by https://github.com/linebender/vello/pull/1301

```
range end index 4 out of range for slice of length 3
Panicked at /Users/nico/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/vello_common-0.0.4/src/encode.rs:1023:42
Backtrace:
   7: core::slice::index::slice_index_fail::do_panic::runtime
   8: core::slice::index::slice_index_fail
   9: vello_common::encode::GradientLut<T>::new
  10: core::cell::once::OnceCell<T>::try_init
  11: vello_cpu::fine::Fine<S,T>::fill
  12: vello_cpu::fine::Fine<S,T>::run_cmd
  13: <vello_cpu::dispatch::single_threaded::SingleThreadedDispatcher as vello_cpu::dispatch::Dispatcher>::rasterize
  14: wpt::test_runners::ref_test::render_html_to_buffer
  15: wpt::test_runners::ref_test::process_ref_test
  16: wpt::test_runners::process_test_file
  17: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
  18: rayon::iter::plumbing::Folder::consume_iter
  19: rayon::iter::plumbing::bridge_producer_consumer::helper
  20: rayon_core::job::StackJob<L,F,R>::run_inline
  21: rayon_core::join::join_context::{{closure}}
  22: rayon::iter::plumbing::bridge_producer_consumer::helper
  23: rayon_core::job::StackJob<L,F,R>::run_inline
  24: rayon_core::join::join_context::{{closure}}
  25: rayon::iter::plumbing::bridge_producer_consumer::helper
  26: rayon_core::join::join_context::{{closure}}
  27: rayon::iter::plumbing::bridge_producer_consumer::helper
  28: rayon_core::job::StackJob<L,F,R>::run_inline
  29: rayon_core::join::join_context::{{closure}}
  30: rayon::iter::plumbing::bridge_producer_consumer::helper
  31: rayon_core::join::join_context::{{closure}}
  32: rayon::iter::plumbing::bridge_producer_consumer::helper
  33: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  34: rayon_core::registry::WorkerThread::wait_until_cold
  35: rayon_core::join::join_context::{{closure}}
  36: rayon::iter::plumbing::bridge_producer_consumer::helper
  37: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  38: rayon_core::registry::WorkerThread::wait_until_cold
  39: rayon_core::registry::ThreadBuilder::run
  40: std::sys::backtrace::__rust_begin_short_backtrace
  41: core::ops::function::FnOnce::call_once{{vtable.shim}}
  42: std::sys::thread::unix::Thread::new::thread_start
  43: __pthread_cond_wait
```

### PR DESCRIPTION
**Pull request by LaurenzV**
Supersedes #1311, closes #1302.

### CODE REVIEW

File: sparse_strips/vello_common/src/encode.rs [hunk 1]
```diff
@@ -270,6 +270,12 @@ fn validate(gradient: &Gradient) -> Result<(), Paint> {
         }
     }
 
+    // Check the last stop as well.
+    let last = gradient.stops.last().unwrap();
+    if last.offset > 1.0 || last.offset < 0.0 || last.offset.is_nan() {
```
Comment (grebmeg) [inline sparse_strips/vello_common/src/encode.rs]: Maybe here and above, the next check would sound a bit more concise + gives you `NaN` rejection fo free?
```rust
    if !(0.0..=1.0).contains(&last.offset) {
        return first;
    }
```

Comment (LaurenzV) [reply sparse_strips/vello_common/src/encode.rs]: Yes, I didn’t do this because I wasn’t sure how efficient this contains check is. I will check on godbolt.

Comment (LaurenzV) [reply sparse_strips/vello_common/src/encode.rs]: Seems to work fine, thanks for the suggestion!
