### PR TITLE
fix(coarse): respect clipping bounds for fill command

### LINKED ISSUE #906: Panic when clipping
The following code panics for me:

```rust
use vello_api::kurbo::{Rect, Shape};
use vello_common::pixmap::Pixmap;
use vello_cpu::RenderContext;

fn main() {
    let width = 2000;
    let height = 2000;
    let mut ctx = RenderContext::new(width, height);
    ctx.save();
    ctx.clip(&Rect::new(400.0, 400.0, 500.0, 500.0).to_path(0.1));
    ctx.fill_rect(&Rect::new(0.0, 0.0, 600.0, 600.0));
    ctx.restore();
    
    let mut pixmap = Pixmap::new(width, height);
    ctx.render_to_pixmap(&mut pixmap);
}
```

```
thread 'main' panicked at /Users/lstampfl/Programming/GitHub/vello/sparse_strips/vello_cpu/src/fine.rs:101:63:
range end index 8128 out of range for slice of length 4032
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/78948ac259253ce89effca1e8bb64d16f4684aa4/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/78948ac259253ce89effca1e8bb64d16f4684aa4/library/core/src/panicking.rs:75:14
   2: core::slice::index::slice_end_index_len_fail::do_panic::runtime
             at /rustc/78948ac259253ce89effca1e8bb64d16f4684aa4/library/core/src/panic.rs:218:21
   3: core::slice::index::slice_end_index_len_fail::do_panic
             at /rustc/78948ac259253ce89effca1e8bb64d16f4684aa4/library/core/src/intrinsics/mod.rs:3240:9
   4: core::slice::index::slice_end_index_len_fail
             at /rustc/78948ac259253ce89effca1e8bb64d16f4684aa4/library/core/src/panic.rs:223:9
   5: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index_mut
             at /Users/lstampfl/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:449:13
   6: <core::ops::range::RangeTo<usize> as core::slice::index::SliceIndex<[T]>>::index_mut
             at /Users/lstampfl/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:527:9
   7: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /Users/lstampfl/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:27:9
   8: vello_cpu::fine::Fine::fill
             at /Users/lstampfl/Programming/GitHub/vello/sparse_strips/vello_cpu/src/fine.rs:101:63
   9: vello_cpu::fine::Fine::run_cmd
             at /Users/lstampfl/Programming/GitHub/vello/sparse_strips/vello_cpu/src/fine.rs:71:17
  10: vello_cpu::render::RenderContext::render_to_pixmap
             at /Users/lstampfl/Programming/GitHub/vello/sparse_strips/vello_cpu/src/render.rs:178:21
  11: main2::main
             at ./src/main2.rs:16:5
  12: core::ops::function::FnOnce::call_once
             at /Users/lstampfl/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

It works fine without clipping. cc @grebmeg

### PR DESCRIPTION
**Pull request by grebmeg**
Fixes #906 

Fix wide tile fill width calculation to respect clip boundaries. This PR fixes an issue where fill commands could generate widths exceeding the wide tile boundaries, causing "index out of range" errors. While the code correctly clamped wide tile indices using the bounding box for strips, it didn’t apply the same clipping logic to fills.

### CODE REVIEW

File: sparse_strips/vello_common/src/coarse.rs [hunk 1]
```diff
@@ -266,7 +267,8 @@ impl Wide {
             // If region should be filled and both strips are on the same row,
             // generate fill commands for the region between them
             if active_fill && strip_y == next_strip.strip_y() {
-                x = x1;
+                // Clamp the fill to the clip bounding box
+                x = x1.max(bbox.x0() * WideTile::WIDTH);
```
Comment (LaurenzV) [inline sparse_strips/vello_common/src/coarse.rs:271]: Is my understanding correct that `x0` refers to the index of the widetile, and not to the absolute coordinate? If so, I think that makes sense!

**Review by LaurenzV — APPROVED** [review]

File: sparse_strips/vello_common/src/coarse.rs (hunk 1 above)
Comment (grebmeg) [reply sparse_strips/vello_common/src/coarse.rs:271]: Yes, it’s the position in wide tile coordinates.

Comment (LaurenzV) [reply sparse_strips/vello_common/src/coarse.rs:271]: Perhaps we could rename it to `wide_tile_x0` in the future for clarity.
