### PR TITLE
Disable the async pipeline by default

### LINKED ISSUE #494: Web Demo hangs after a minute
After about a minute or two, the web demo (http://linebender.org/vello/) hangs.

Zulip ref: https://xi.zulipchat.com/#narrow/stream/197075-gpu/topic/Vello.3A.20wasm.20web.20demo

Seemingly because the GpuProfiler?

Stack trace:
Stack

### PR DESCRIPTION
**Pull request by DJMcNab**
The async pipeline is not wired up to do robust readback, so it has few advantages (see #366)

This PR also enables the non-async pipeline's interaction with the GPU profiling (which should make it work on wasm)

@simbleau this might also properly fix #494, incidentally.

### CODE REVIEW

File: examples/with_winit/src/lib.rs [hunk 1]
```diff
@@ -451,8 +461,9 @@ fn run(
                             .surface
                             .get_current_texture()
                             .expect("failed to get surface texture");
-                        #[cfg(not(target_arch = "wasm32"))]
-                        {
+                        // Note: we don't run the async/"robust" pipeline, as
+                        // it requires more async wiring for the readback.
```
Comment (simbleau) [inline examples/with_winit/src/lib.rs:465]: Could we get more detail here? What is meant by "async wiring" - Is this a limitation of !Send futures, single-threaded wasm, etc. - What *exactly* is the issue on WASM that we aren't doing async pipelines there?

**Review by simbleau — APPROVED** [review]

File: examples/with_winit/src/lib.rs (hunk 1 above)
Comment (DJMcNab) [reply examples/with_winit/src/lib.rs:465]: The thread is [#gpu > async on wasm](https://xi.zulipchat.com/#narrow/stream/197075-gpu/topic/async.20on.20wasm). Broadly, the issue is: if we spawn a future, that needs to keep hold of the `scene`. But that's incompatible with lifetimes of keeping the scene around (to reuse allocations, etc.)

In theory, we should do this much more carefully, but we haven't yet. That might also be useful in contexts outside of browsers too, allowing multi-threaded scene rendering
